KS-9-5 lesson9 task5 five ingredients
IEZH/KotlinSprint pull request #41
Opened 2023-03-23 07:49 UTC by IEZH

2023-03-23 07:51 UTC, IEZH commented
немножко не доделал, не хватает точки в конце списка, но хз как это делается, я видимо еще не проходил такое)

2023-03-23 14:09 UTC, ievetrov requested changes
найти индекс , который находится по последнему элементу и приконкатенируй к нему точку)

2023-03-24 14:54 UTC, ievetrov requested changes

2023-03-24 14:54 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    println(listOsIngredientsWithoutDouble)
>  – все элементы списка выведены в одну строку, разделяя слова запятыми;
Про квадратные скобки ничего не сказано )
Попробуй метод joinToString, обрати внимание на параметры метода

2023-03-24 14:54 UTC, ievetrov commented on src/main/kotlin/lesson_9/lesson_9_task_5.kt
> +    listOsIngredientsWithoutDouble[4] = listOsIngredientsWithoutDouble[4].plus(".")
В условии сказано:
>  – первое слово должно быть напечатано с заглавной буквы, в конце списка должна стоять точка.
Нет ничего про "элемент с индексом 4". Давай будем добавлять точку именно в последний элемент

2023-03-27 20:58 UTC, ievetrov approved these changes
огонек!

2023-03-30 09:30 UTC, merged