Ks 11 2 bio
IEZH/KotlinSprint pull request #48
Opened 2023-05-27 13:08 UTC by IEZH

2023-05-28 08:16 UTC, ievetrov requested changes

2023-05-28 08:16 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_2.kt
> +            bio = ""
ты уже указал в классе значение по умолчанию для этого свойства. при создании объекта не нужно задавать его еще раз.

2023-05-30 17:00 UTC, IEZH commented on src/main/kotlin/lesson_11/lesson_11_task_2.kt
> +            bio = ""
точняк, тупанул

2023-05-31 15:14 UTC, ievetrov requested changes

2023-05-31 15:14 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_2.kt
> +        } else return
здесь вместо return можно зациклить функцию и тогда она будет вызываться до тех пор, пока пользователь не введет корректный пароль
`else {
changePassword()
}`

2023-05-31 15:14 UTC, ievetrov commented on src/main/kotlin/lesson_11/lesson_11_task_2.kt
> +        println(id)
лучше будет сделать для вывода одну строку, используя символ $. например:
`println("User: $id $login")`

2023-06-22 12:04 UTC, ievetrov approved these changes

2023-06-23 16:37 UTC, merged