KS-12-5 lesson12 task5 weather program
IEZH/KotlinSprint pull request #54
Opened 2023-07-04 08:10 UTC by IEZH

2023-07-04 08:11 UTC, IEZH commented
вот такой я гений 😁😁😁

2023-07-05 21:20 UTC, ievetrov requested changes

2023-07-05 21:20 UTC, ievetrov commented on src/main/kotlin/lesson_12/lesson_12_task_5.kt
> +    val averageTemperatureOfDay = sumTemperatureOfDay / weatherList.size
отлично, но попробуй применить функцию average() для поиска среднего значения

2023-07-08 12:39 UTC, ievetrov approved these changes

2023-07-09 10:51 UTC, merged